spring.profiles.active: "simple" #none, simple

#logging
logging.level.root: "WARN"
logging.level.org.springframework: "WARN"
logging.level.org.springframework.integration: "INFO"
logging.level.org.goafabric: "INFO"
