server:
  port: 50100
  tomcat.threads.max: 20


#profile
spring.profiles.active: "simple" #none, simple, simpler, file, jdbc, batch, service, tcp, kafka

#persistence
spring.datasource.url: jdbc:h2:mem:person
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.datasource.hikari.maximum-pool-size: "10"
spring.datasource.hikari.connection-timeout: "10000"

#logging
logging.level.root: "WARN"
logging.level.org.springframework: "WARN"
logging.level.org.springframework.integration: "WARN"
logging.level.org.goafabric: "INFO"
